import Service from '@ember/service';
import { A } from '@ember/array';
import PagesPageController from '../controllers/pages/page';

export default class PageListsService extends Service {
  items = A([
    {
      route: 'pages.page',
      page_name: 'introduction',
      title: 'Introduction',
      content:
        'Introduction Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas.',
    },
    {
      route: 'pages.page',
      page_name: 'tutorial',
      title: 'Tutorial',
      content:
        'Tutorial Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas.',
    },
    {
      route: 'pages.page',
      page_name: 'concept1',
      title: 'Concept 1',
      content:
        'Cancept 1 Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas.',
    },
    {
      route: 'pages.page',
      page_name: 'concept2',
      title: 'Concept 2',
      content:
        'Concept 2 Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas.',
    },
    {
      route: 'pages.page',
      page_name: 'concept3',
      title: 'Concept 3',
      content:
        'Concept 3 Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas.',
    },
    {
      route: 'pages.page',
      page_name: 'summary',
      title: 'Summary',
      content:
        'Summary Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas. Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti molestias consectetur ullam, nemo aliquid unde iusto recusandae aut eaque dolor, consequuntur laboriosam non veniam nihil iste quia, animi eveniet debitis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum assumenda in, consequatur aliquam debitis, hic porro saepe amet ipsam, rem id! Illo quasi molestias incidunt eius perspiciatis sunt voluptates beatae. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum delectus illum necessitatibus doloremque soluta doloribus facere ut, nemo nulla repellendus! Delectus rem totam, eligendi rerum quo sapiente maiores ad? Expedita! Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa iusto consectetur temporibus numquam? Laborum eius autem molestias soluta rerum sit, quae velit veniam, earum cupiditate, unde quas sapiente! Debitis, quas.',
    },
  ]);

  add(item) {
    this.items.pushObject(item);
  }
}
